---
- hosts: servers
  tasks:
  - name: Create directory
    file: path=/home/ubuntu/downloads state=directory mode=775 owner=ubuntu 
  - name: Copy file
    copy:
       src: /home/ubuntu/ansible_example/downloads/spark-3.1.2-bin-hadoop3.2.tgz
       dest: /home/ubuntu/downloads/
       owner: ubuntu
       mode: '0644'
