---
- hosts: servers
  user: ubuntu
  
  tasks:
    - lineinfile:
       path: /tmp/testfile
       line: '192.168.1.99 foo.lab.net foo'
    - lineinfile:
       path: /tmp/testfile
       line: 'PATH=${SPARK_HOME}/bin:${PATH}'

