---
- hosts: jobservert1
  user: ubuntu
  become: yes
  
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install java
      apt:
        name: default-jre
        state: present

