--- 
- name: Start Master
  user: ubuntu
  hosts: jobservert1
  become: yes

  tasks:
          - name: Run Job Server Start Command
            command: /opt/spark/sbin/start-worker.sh spark://sparkmaster:7077
